name: Ping Azure Health Endpoint

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes UTC
  workflow_dispatch:        # Optional: allow manual run from GitHub

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Ping /health endpoint with retry
        run: |
          echo "Pinging Azure /health endpoint..."
          for i in {1..10}; do
            echo "Attempt $i..."
            http_status=$(curl -s -o /dev/null -w "%{http_code}" https://rd1timesheet.azurewebsites.net/health || echo "000")
            echo "Status: $http_status"
            if [ "$http_status" -eq 200 ]; then
              echo "App is healthy!"
              exit 0
            fi
            sleep 15
          done
          echo "App did not become healthy after 10 attempts."
          exit 1
